name = "keystatic-admin"
main = ".open-next/worker.js"
compatibility_date = "2025-06-02"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NODE_ENV = "production"
KEYSTATIC_GITHUB_CLIENT_ID = "Ov23liRKe9S4RSOwMTPR"
KEYSTATIC_GITHUB_CLIENT_SECRET = "c0a5a61089e78d6b9c1af997bc0d562557a16a39"
KEYSTATIC_SECRET = "ks_yimeng_zpc_2026_xK9mP2vQ7wR4x"
